name: Get PR Info Action
description: Get information from a pull request
outputs:
  additions:
    description: number of code additions
  deletions:
    description: number of code deletions
  changed_files:
    description: number of changed files
  commits:
    description: number of commits included in the pull request
  assignee:
    description: pull request assignee
  number:
    description: pull request number
  title:
    description: title of the pull request
  body:
    description: body of the pull request
  created_at:
    description: timestamp when the pull request was created
  updated_at:
    description: timestamp when the pull request was updated
  url:
    description: url of the pull request
  base_branch:
    description: destination branch of the pull request
  head_branch:
    description: source branch of the pull request
  draft:
    description: boolean representing if this pr is a draft
runs:
  using: node12
  main: dist/index.js
branding:
  color: blue
  icon: arrow-left-circle
