name: Notify

on: [push]

jobs:
  notify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: Brymastr/slack-action@v1
        name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          template: "./.github/workflows/push.json"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: npm ci

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - uses: Brymastr/slack-action@v1
        name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          template: "./.github/workflows/build.json"
          job_status: ${{ job.status }}
